### ISSUE TITLE
My Tenancies not displaying

### ISSUE THREAD

**Issue by evcom3** [Alchemication/GrandLord#10]
Currently logged in user id in now stored in the session, unfortunately tenancies are not displaying at the moment, needs to be investigated...

**Comment by Alchemication** [comment]
Check this out Piotr:

https://github.com/Alchemication/GrandLord/blob/master/application/controllers/TenancyController.php#L94

https://github.com/Alchemication/GrandLord/blob/master/application/controllers/PropertyController.php#L47

**Comment by evcom3** [comment]
That's sorted now, Thank you.
